site_name: Accept Ignorance | Hao Ma, Ph.D.
theme:
  name: material
  custom_dir: overrides

  logo: assets/logo.jpeg
  # Home: index.md 
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - navigation.indexes 
    - navigation.top
    - header.autohide
    - announce.dismiss


  palette: 
    - media: "(prefers-color-scheme: light)"
      scheme: light-scheme
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  font:
    text: Gaegu
    code: Roboto Mono
extra_css:
  - stylesheets/extra.css
extra_javascript:
  - javascripts/extra.js 

nav:
  - Home: ./index.md
  - Machine Learning:
    - Machine-Learning/index.md
    - Page 1: Machine-Learning/page-1.md
  - Web and Cloud:
    - Web-and-Cloud/index.md
    - Page 1: Web-and-Cloud/page-1.md

  - Tags: tags.md

plugins:
  - tags:
      tags_file: tags.md
  - search
extra:
  generator: false
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/haoma7

    - icon: fontawesome/brands/facebook
      link: https://scholar.google.com/citations?user=F44gDZ4AAAAJ
    
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/mahao/

