site_name: Daring and Persistent | Hao Ma, Ph.D.
theme:
  name: material
  custom_dir: overrides

  logo: assets/logo.jpeg
  # Home: index.md 
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.expand
    - navigation.indexes 
    - navigation.top
    - header.autohide
    - announce.dismiss


  palette: 
    - media: "(prefers-color-scheme: light)"
      scheme: light-scheme
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  font:
    text: Gaegu
    code: Roboto Mono
extra_css:
  - stylesheets/extra.css
extra_javascript:
  - javascripts/extra.js 
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
markdown_extensions:
  - def_list
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details

  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format


nav:
  - Home: ./index.md
  - Learning:
    - learning/index.md
    - 'Machine Learning': 
        - learning/machine-learning/index.md 
        - 'Restricted Boltzmann Machine': learning/machine-learning/rbm.md 
        - 'Head First Transformer': learning/machine-learning/transformer.md
    - 'Web and Cloud': 
        - learning/web-and-cloud/index.md
        - 'Vue.js': learning/web-and-cloud/vuejs.md
    - 'Networks':
        - learning/networks/index.md
  - Teaching:
    - 'Teaching': teaching/index.md
    - 'Teaching Philosophy': teaching/teaching-philosophy.md
    - 'CSIT@KPU': teaching/kpu.md
    - 'Thoughts on Higher-Ed': teaching/high-ed-books.md
  - Life:
    - life/index.md
  - Tags: tags.md

plugins:
  - tags:
      tags_file: tags.md
  - search
  - enumerate-headings:
      toc_depth: 1
      strict: true
      increment_across_pages: false
      exclude:
        - tags.md
        - index.md
extra:
  generator: false
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/haoma7

    - icon: fontawesome/brands/facebook
      link: https://scholar.google.com/citations?user=F44gDZ4AAAAJ
    
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/mahao/

